name: Build and Push Docker Image To AWS PRIVATE ECR
on:
  workflow_dispatch
  # push:
  #   branches:
  #     - main

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

      # github actions 에서 빌드
    - run: docker buildx build -t app .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # aws-region: us-east-1
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR Private
      id: login-ecr-private
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: private

    - name: Build, tag, and push docker image to Amazon ECR private
      env:
        REGISTRY: ${{ secrets.AWS_ECR_PRIVATE }}  # ECR 주소
        REPOSITORY: first-ecr-private            # 리포지토리 이름
        IMAGE_TAG: latest                        # 이미지 태그
      run: |
        # AWS ECR 로그인
        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $REGISTRY
    
        # ECR 리포지토리 생성 (리포지토리가 없을 경우)
        aws ecr create-repository --repository-name $REPOSITORY --region ap-northeast-2 || echo "Repository already exists"

        # Docker 이미지 빌드
        docker build -t app .

        # Docker 이미지 ECR 레지스트리로 태깅
        docker tag app:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG

        # Docker 이미지 ECR로 푸시
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
